// SDD Live Status — generated by /sdd:dashboard
// Skills update this file during execution to show real-time progress
window.__SDD_LIVE_UPDATE({
  "sessionId": null,
  "currentStage": null,
  "status": "idle",
  "lastHeartbeat": "2026-03-24T18:58:42.917370+00:00",
  "progress": null,
  "message": "Dashboard generated. Waiting for pipeline activity.",
  "history": []
});